name: Release crazy build

on:
  schedule:
    - cron: '0 1 * * 4'

  workflow_dispatch:

jobs:

  build:
    name: Build product and upload it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo clean && cargo build --release

      - name: Rename
        run: mv target/release/conch target/release/conch_v0.0.0-crazy

      - name: Upload build product
        uses: actions/upload-artifact@v3
        with:
          name: conch_v0.0.0-crazy
          path: target/release/conch_v0.0.0-crazy

  push-to-registries:
    name: Pack image and push it to multi registries
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download build product
        uses: actions/download-artifact@v3
        with:
          name: conch_v0.0.0-crazy

      - name: Move to target
        run: mkdir -p target/release/ && mv conch_v0.0.0-crazy target/release/conch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: qianjunakasumi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            qianjunakasumi/senjuko-conch:crazy
            ghcr.io/qianjunakasumi/senjuko-conch:crazy
            qianjunakasumi/senjuko-conch:latest
            ghcr.io/qianjunakasumi/senjuko-conch:latest
