name: Update version

on:
  schedule:
    - cron: '0 1 * * 1'
    - cron: '0 1 * * 4'
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: tibdex/github-app-token@v1
        name: Generate token
        id: generate-token
        with:
          app_id: 242446
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update version
        id: update-version
        working-directory: ./actions/stepper
        run: |
          go run -v ./...
          echo "fileName=${cat download_filename}" >> $GITHUB_OUTPUT
          echo "url=${cat download_url}" >> $GITHUB_OUTPUT
          rm -f download_filename
          rm -f download_url

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: prefğŸ‘½ï¸version åŒæ­¥è‡³ä¸Šæ¸¸ç‰ˆæœ¬
          signoff: true
          branch: pref/bump-version
          delete-branch: true
          title: autoâš™ï¸action åŒæ­¥è‡³ä¸Šæ¸¸ç‰ˆæœ¬
          body: |
            ## æ£€æŸ¥æ¸…å•
            
            - [ ] JceStruct å·²æ˜¯æœ€æ–°
            
            <details>
            <summary>å¼€å‘è€…å·¥å…·</summary>
            
            - ä¸‹è½½é“¾æ¥: [${{ steps.update-version.outputs.fileName }}](${{ steps.update-version.outputs.url }})   
            </details>
