name: UpdateVersion

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Change directory
      run: cd ./actions/stepper/

    - name: Update Version
      run: go run -v ./...

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: prefğŸ‘½ï¸ æ›´æ–°ç‰ˆæœ¬
        branch: pref/version
        delete-branch: true
        title: ğŸ‘½ï¸ æ›´æ–°ç‰ˆæœ¬
        body: |
          - [ ] JceStruct å·²æ˜¯æœ€æ–°
        assignees: qianjunakasumi
        reviewers: qianjunakasumi
